apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - secret.yaml

configMapGenerator:
  - name: omnipanel-go-config
    files:
      - config.json

images:
  - name: omnipanel-go
    newName: git.antonsblog.org/atwi/omnipanel-go
    newTag: 58d0a8a

patches:
  - target:
      kind: Deployment
      name: omnipanel-go
    patch: |
      - op: add
        path: /spec/template/spec/imagePullSecrets
        value:
          - name: omnipanel-go-registry
  - target:
      kind: HTTPRoute
      name: omnipanel-go
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: omnipanel.mydomain.com
  - target:
      kind: Ingress
      name: omnipanel-go
    patch: |
      - op: add
        path: /metadata/annotations/cert-manager.io~1cluster-issuer
        value: letsencrypt
      - op: replace
        path: /spec/rules/0/host
        value: omni.antonsblog.org
      - op: replace
        path: /spec/tls/0/hosts/0
        value: omni.antonsblog.org
      - op: replace
        path: /spec/tls/0/secretName
        value: omni-antonsblog-org-tls