apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: omnipanel-go
    newTag: v1.0.0

patches:
  - target:
      kind: HTTPRoute
      name: omnipanel-go
    patch: |
      - op: replace
        path: /spec/hostnames/0
        value: omnipanel.mydomain.com
  - target:
      kind: Ingress
      name: omnipanel-go
    patch: |
      - op: replace
        path: /spec/rules/0/host
        value: omnipanel.mydomain.com
