apiVersion: v1
kind: Secret
metadata:
  name: omnipanel-go-registry
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "git.antonsblog.org": {
          "username": "atwi",
          "password": "51268e90cef98a7ba30f378d90761ad99a74a71f",
          "auth": "YXR3aTo1MTI2OGU5MGNlZjk4YTdiYTMwZjM3OGQ5MDc2MWFkOTlhNzRhNzFm"
        }
      }
    }