apiVersion: v1
kind: Secret
metadata:
  name: omnipanel-go-registry
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "git.antonsblog.org": {
          "username": "USERNAME",
          "password": "PASSWORD",
          "auth": "BASE64 USERNAME:PASSWORD"
        }
      }
    }
