apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - pvc.yaml
  - service.yaml

  # Choose ONE of the following ingress methods:
  # - httproute.yaml
  - ingress.yaml

images:
  - name: omnipanel-go
    newTag: latest
